install:
- bzip2 -d tst2.bz2 
- python3 esp_input_gen.py
- git clone https://github.com/psksvp/espresso-ab-1.0
- cd espresso-ab-1.0
- ./configure CFLAGS="-O3 -mtune=native -march=native"
- make 
- cp ./src/espresso ../
- cd ..

script:
- ./espresso out > esp_out1 &
- ./smp2.sh
- test -s esp_out1 && bzip2 -9 esp_out1

deploy:
  skip_cleanup: true
  provider: releases
  api_token: "${MY_API}"
  file: "esp_out1.bz2"
  on:
    tags: false
